<?php
$this->headTitle('Step 2 - Choose a flight');

$form->get('submit')->setAttributes(array('class' => 'btn btn-primary'));

$form->prepare();
?>

<h1>Flight Reservation - Step 2 - Choose a flight</h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="list-group">
            <?= $this->formElement($form->get('available_departure_time')); ?>
        </div>                

        <div class="list-group">
            <?= $this->formElement($form->get('available_return_time')); ?>
        </div>        
        
        <div class="form-group">
            <?= $this->formElement($form->get('submit')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>        
    
</div>    

<?php /* @todo move to .js file */ ?>
<script>

    $(document).ready(function () {
        radioComponentDeparturesClass = 'js-radiocomponent_departure'; //global
        radioButtonDeparturesClass = 'js-radiobutton_departure'; //global

        radioComponentReturnsClass = 'js-radiocomponent_return'; //global
        radioButtonReturnsClass = 'js-radiobutton_return'; //global

        // @todo refactor this init
        /*
        $('#js-radiolabel_departure_0').addClass('radioCustomSelected');
        
        if($("#js-radiolabel_return_0").length !== 0) {
            $('#js-radiolabel_return_0').addClass('radioCustomSelected');
        }*/

        $("." + radioComponentDeparturesClass).click(function (event) {
            event.preventDefault();
            
            resetCheckedDeparturesRadioButtons(); // reset all
            checkRadiobutton(this); //check only this
            
            console.log(this);
        });
        
        $("." + radioComponentReturnsClass).click(function (event) {
            event.preventDefault();
            
            resetCheckedReturnsRadioButtons(); // reset all
            checkRadiobutton(this); //check only this
            
            //console.log(this);
        });

        function checkRadiobutton(radioButtonElem) {            
            $(radioButtonElem).addClass('radioCustomSelected');
            var idRadiobutton = $(radioButtonElem).data('for_id');           
            $('#' + idRadiobutton).attr('checked', 'checked');            
        }

        function resetCheckedDeparturesRadioButtons() {
            removeCheckedRadioButtonsByClass(radioButtonDeparturesClass);
            removeCheckStyleRadioComponentByClass(radioComponentDeparturesClass);
        }

        function resetCheckedReturnsRadioButtons() {
            removeCheckedRadioButtonsByClass(radioButtonReturnsClass);
            removeCheckStyleRadioComponentByClass(radioComponentReturnsClass);
        }


        function removeCheckedRadioButtonsByClass(className){
             $('.' + className).removeAttr('checked');
        }

        function removeCheckStyleRadioComponentByClass(className){
             $('.' + className).removeClass('radioCustomSelected');
        }

    });
</script>    



<?php /* @todo move to .css file */ ?>
<style>
    .radioCustomSelected{
        border-color: blue;
        background-color: #87CEFA;
    }


    .list-group-item {
        user-select: none;
    }

    .list-group input[type="radio"] {
        display: none;
    }

    .list-group input[type="radio"] + .list-group-item {
        cursor: pointer;
    }

    .list-group input[type="radio"] + .list-group-item:before {
        content: "\2022";
        color: transparent;
        font-weight: bold;
        margin-right: 1em;
    }

    .list-group input[type="radio"]:checked + .list-group-item {
        background-color: #0275D8;
        color: #FFF;
    }

    .list-group input[type="radio"]:checked + .list-group-item:before {
        color: inherit;
    }    
</style>    

